# Generated by Django 5.0.2 on 2024-11-14 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.customer')),
            ],
        ),
    ]
