# Generated by Django 5.0.2 on 2024-11-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_remove_todo_customers_todo_user_alter_todo_todo_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
